### ISSUE TITLE
its not working the handshake menu

### ISSUE THREAD

**Issue by KiraxD** [DEADSEC-SECURITY/CODEX#20]
Traceback (most recent call last):
  File "/home/kali/Desktop/CODEX/codex.py", line 405, in HANDSHAKE
    os.path.mkdir(Dir)
    ^^^^^^^^^^^^^
AttributeError: module 'posixpath' has no attribute 'mkdir'. Did you mean: 'isdir'?

**Comment by KiraxD** [comment]
its same with all the menus

**Comment by KiraxD** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'Data/Aircrack-ng/AiroDumpOutPut-01.csv'

**Comment by DEADSEC-SECURITY** [comment]
This is a very old repo that is sort abandoned so it doesnt have support for newer versions of python. What version of python are you running?
